// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firstTest.proto

package com.example.grpcprotocol;

public interface CalculateSumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcprotocol.CalculateSumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated int32 number = 2;</code>
   * @return A list containing the number.
   */
  java.util.List<java.lang.Integer> getNumberList();
  /**
   * <code>repeated int32 number = 2;</code>
   * @return The count of number.
   */
  int getNumberCount();
  /**
   * <code>repeated int32 number = 2;</code>
   * @param index The index of the element to return.
   * @return The number at the given index.
   */
  int getNumber(int index);
}
