// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firstTest.proto

package com.example.grpcprotocol;

public interface QueryInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcprotocol.QueryInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string uuid = 3;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 3;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>repeated .grpcprotocol.subjectMarks records = 4;</code>
   */
  java.util.List<com.example.grpcprotocol.subjectMarks> 
      getRecordsList();
  /**
   * <code>repeated .grpcprotocol.subjectMarks records = 4;</code>
   */
  com.example.grpcprotocol.subjectMarks getRecords(int index);
  /**
   * <code>repeated .grpcprotocol.subjectMarks records = 4;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .grpcprotocol.subjectMarks records = 4;</code>
   */
  java.util.List<? extends com.example.grpcprotocol.subjectMarksOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .grpcprotocol.subjectMarks records = 4;</code>
   */
  com.example.grpcprotocol.subjectMarksOrBuilder getRecordsOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; subjectTeachs = 5;</code>
   */
  int getSubjectTeachsCount();
  /**
   * <code>map&lt;string, string&gt; subjectTeachs = 5;</code>
   */
  boolean containsSubjectTeachs(
      java.lang.String key);
  /**
   * Use {@link #getSubjectTeachsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getSubjectTeachs();
  /**
   * <code>map&lt;string, string&gt; subjectTeachs = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getSubjectTeachsMap();
  /**
   * <code>map&lt;string, string&gt; subjectTeachs = 5;</code>
   */

  java.lang.String getSubjectTeachsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; subjectTeachs = 5;</code>
   */

  java.lang.String getSubjectTeachsOrThrow(
      java.lang.String key);
}
