// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firstTest.proto

package com.example.grpcprotocol;

/**
 * Protobuf type {@code grpcprotocol.QueryInfoRequest}
 */
public final class QueryInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcprotocol.QueryInfoRequest)
    QueryInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryInfoRequest.newBuilder() to construct.
  private QueryInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryInfoRequest() {
    school_ = "";
    personalInfoRecords_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryInfoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryInfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            school_ = s;
            break;
          }
          case 24: {

            isBoy_ = input.readBool();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              personalInfoRecords_ = new java.util.ArrayList<com.example.grpcprotocol.personalInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            personalInfoRecords_.add(
                input.readMessage(com.example.grpcprotocol.personalInfo.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              familyInfo_ = com.google.protobuf.MapField.newMapField(
                  FamilyInfoDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            familyInfo__ = input.readMessage(
                FamilyInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            familyInfo_.getMutableMap().put(
                familyInfo__.getKey(), familyInfo__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        personalInfoRecords_ = java.util.Collections.unmodifiableList(personalInfoRecords_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetFamilyInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpcprotocol.QueryInfoRequest.class, com.example.grpcprotocol.QueryInfoRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <pre>
   *id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int SCHOOL_FIELD_NUMBER = 2;
  private volatile java.lang.Object school_;
  /**
   * <code>string school = 2;</code>
   * @return The school.
   */
  @java.lang.Override
  public java.lang.String getSchool() {
    java.lang.Object ref = school_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      school_ = s;
      return s;
    }
  }
  /**
   * <code>string school = 2;</code>
   * @return The bytes for school.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSchoolBytes() {
    java.lang.Object ref = school_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      school_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISBOY_FIELD_NUMBER = 3;
  private boolean isBoy_;
  /**
   * <code>bool isBoy = 3;</code>
   * @return The isBoy.
   */
  @java.lang.Override
  public boolean getIsBoy() {
    return isBoy_;
  }

  public static final int PERSONALINFORECORDS_FIELD_NUMBER = 4;
  private java.util.List<com.example.grpcprotocol.personalInfo> personalInfoRecords_;
  /**
   * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.grpcprotocol.personalInfo> getPersonalInfoRecordsList() {
    return personalInfoRecords_;
  }
  /**
   * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.grpcprotocol.personalInfoOrBuilder> 
      getPersonalInfoRecordsOrBuilderList() {
    return personalInfoRecords_;
  }
  /**
   * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
   */
  @java.lang.Override
  public int getPersonalInfoRecordsCount() {
    return personalInfoRecords_.size();
  }
  /**
   * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
   */
  @java.lang.Override
  public com.example.grpcprotocol.personalInfo getPersonalInfoRecords(int index) {
    return personalInfoRecords_.get(index);
  }
  /**
   * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
   */
  @java.lang.Override
  public com.example.grpcprotocol.personalInfoOrBuilder getPersonalInfoRecordsOrBuilder(
      int index) {
    return personalInfoRecords_.get(index);
  }

  public static final int FAMILYINFO_FIELD_NUMBER = 5;
  private static final class FamilyInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_FamilyInfoEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> familyInfo_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetFamilyInfo() {
    if (familyInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FamilyInfoDefaultEntryHolder.defaultEntry);
    }
    return familyInfo_;
  }

  public int getFamilyInfoCount() {
    return internalGetFamilyInfo().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; familyInfo = 5;</code>
   */

  @java.lang.Override
  public boolean containsFamilyInfo(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFamilyInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFamilyInfoMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getFamilyInfo() {
    return getFamilyInfoMap();
  }
  /**
   * <code>map&lt;string, string&gt; familyInfo = 5;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getFamilyInfoMap() {
    return internalGetFamilyInfo().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; familyInfo = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getFamilyInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFamilyInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; familyInfo = 5;</code>
   */
  @java.lang.Override

  public java.lang.String getFamilyInfoOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetFamilyInfo().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(school_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, school_);
    }
    if (isBoy_ != false) {
      output.writeBool(3, isBoy_);
    }
    for (int i = 0; i < personalInfoRecords_.size(); i++) {
      output.writeMessage(4, personalInfoRecords_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFamilyInfo(),
        FamilyInfoDefaultEntryHolder.defaultEntry,
        5);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(school_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, school_);
    }
    if (isBoy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isBoy_);
    }
    for (int i = 0; i < personalInfoRecords_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, personalInfoRecords_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetFamilyInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      familyInfo__ = FamilyInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, familyInfo__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpcprotocol.QueryInfoRequest)) {
      return super.equals(obj);
    }
    com.example.grpcprotocol.QueryInfoRequest other = (com.example.grpcprotocol.QueryInfoRequest) obj;

    if (getId()
        != other.getId()) return false;
    if (!getSchool()
        .equals(other.getSchool())) return false;
    if (getIsBoy()
        != other.getIsBoy()) return false;
    if (!getPersonalInfoRecordsList()
        .equals(other.getPersonalInfoRecordsList())) return false;
    if (!internalGetFamilyInfo().equals(
        other.internalGetFamilyInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + SCHOOL_FIELD_NUMBER;
    hash = (53 * hash) + getSchool().hashCode();
    hash = (37 * hash) + ISBOY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsBoy());
    if (getPersonalInfoRecordsCount() > 0) {
      hash = (37 * hash) + PERSONALINFORECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getPersonalInfoRecordsList().hashCode();
    }
    if (!internalGetFamilyInfo().getMap().isEmpty()) {
      hash = (37 * hash) + FAMILYINFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFamilyInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpcprotocol.QueryInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpcprotocol.QueryInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcprotocol.QueryInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcprotocol.QueryInfoRequest)
      com.example.grpcprotocol.QueryInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetFamilyInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableFamilyInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpcprotocol.QueryInfoRequest.class, com.example.grpcprotocol.QueryInfoRequest.Builder.class);
    }

    // Construct using com.example.grpcprotocol.QueryInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPersonalInfoRecordsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      school_ = "";

      isBoy_ = false;

      if (personalInfoRecordsBuilder_ == null) {
        personalInfoRecords_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        personalInfoRecordsBuilder_.clear();
      }
      internalGetMutableFamilyInfo().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpcprotocol.FirstTestServiceProtos.internal_static_grpcprotocol_QueryInfoRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpcprotocol.QueryInfoRequest getDefaultInstanceForType() {
      return com.example.grpcprotocol.QueryInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpcprotocol.QueryInfoRequest build() {
      com.example.grpcprotocol.QueryInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpcprotocol.QueryInfoRequest buildPartial() {
      com.example.grpcprotocol.QueryInfoRequest result = new com.example.grpcprotocol.QueryInfoRequest(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.school_ = school_;
      result.isBoy_ = isBoy_;
      if (personalInfoRecordsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          personalInfoRecords_ = java.util.Collections.unmodifiableList(personalInfoRecords_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.personalInfoRecords_ = personalInfoRecords_;
      } else {
        result.personalInfoRecords_ = personalInfoRecordsBuilder_.build();
      }
      result.familyInfo_ = internalGetFamilyInfo();
      result.familyInfo_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpcprotocol.QueryInfoRequest) {
        return mergeFrom((com.example.grpcprotocol.QueryInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpcprotocol.QueryInfoRequest other) {
      if (other == com.example.grpcprotocol.QueryInfoRequest.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getSchool().isEmpty()) {
        school_ = other.school_;
        onChanged();
      }
      if (other.getIsBoy() != false) {
        setIsBoy(other.getIsBoy());
      }
      if (personalInfoRecordsBuilder_ == null) {
        if (!other.personalInfoRecords_.isEmpty()) {
          if (personalInfoRecords_.isEmpty()) {
            personalInfoRecords_ = other.personalInfoRecords_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePersonalInfoRecordsIsMutable();
            personalInfoRecords_.addAll(other.personalInfoRecords_);
          }
          onChanged();
        }
      } else {
        if (!other.personalInfoRecords_.isEmpty()) {
          if (personalInfoRecordsBuilder_.isEmpty()) {
            personalInfoRecordsBuilder_.dispose();
            personalInfoRecordsBuilder_ = null;
            personalInfoRecords_ = other.personalInfoRecords_;
            bitField0_ = (bitField0_ & ~0x00000001);
            personalInfoRecordsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPersonalInfoRecordsFieldBuilder() : null;
          } else {
            personalInfoRecordsBuilder_.addAllMessages(other.personalInfoRecords_);
          }
        }
      }
      internalGetMutableFamilyInfo().mergeFrom(
          other.internalGetFamilyInfo());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpcprotocol.QueryInfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpcprotocol.QueryInfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object school_ = "";
    /**
     * <code>string school = 2;</code>
     * @return The school.
     */
    public java.lang.String getSchool() {
      java.lang.Object ref = school_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        school_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string school = 2;</code>
     * @return The bytes for school.
     */
    public com.google.protobuf.ByteString
        getSchoolBytes() {
      java.lang.Object ref = school_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        school_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string school = 2;</code>
     * @param value The school to set.
     * @return This builder for chaining.
     */
    public Builder setSchool(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      school_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string school = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchool() {
      
      school_ = getDefaultInstance().getSchool();
      onChanged();
      return this;
    }
    /**
     * <code>string school = 2;</code>
     * @param value The bytes for school to set.
     * @return This builder for chaining.
     */
    public Builder setSchoolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      school_ = value;
      onChanged();
      return this;
    }

    private boolean isBoy_ ;
    /**
     * <code>bool isBoy = 3;</code>
     * @return The isBoy.
     */
    @java.lang.Override
    public boolean getIsBoy() {
      return isBoy_;
    }
    /**
     * <code>bool isBoy = 3;</code>
     * @param value The isBoy to set.
     * @return This builder for chaining.
     */
    public Builder setIsBoy(boolean value) {
      
      isBoy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isBoy = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsBoy() {
      
      isBoy_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.example.grpcprotocol.personalInfo> personalInfoRecords_ =
      java.util.Collections.emptyList();
    private void ensurePersonalInfoRecordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        personalInfoRecords_ = new java.util.ArrayList<com.example.grpcprotocol.personalInfo>(personalInfoRecords_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpcprotocol.personalInfo, com.example.grpcprotocol.personalInfo.Builder, com.example.grpcprotocol.personalInfoOrBuilder> personalInfoRecordsBuilder_;

    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public java.util.List<com.example.grpcprotocol.personalInfo> getPersonalInfoRecordsList() {
      if (personalInfoRecordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(personalInfoRecords_);
      } else {
        return personalInfoRecordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public int getPersonalInfoRecordsCount() {
      if (personalInfoRecordsBuilder_ == null) {
        return personalInfoRecords_.size();
      } else {
        return personalInfoRecordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public com.example.grpcprotocol.personalInfo getPersonalInfoRecords(int index) {
      if (personalInfoRecordsBuilder_ == null) {
        return personalInfoRecords_.get(index);
      } else {
        return personalInfoRecordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder setPersonalInfoRecords(
        int index, com.example.grpcprotocol.personalInfo value) {
      if (personalInfoRecordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.set(index, value);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder setPersonalInfoRecords(
        int index, com.example.grpcprotocol.personalInfo.Builder builderForValue) {
      if (personalInfoRecordsBuilder_ == null) {
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.set(index, builderForValue.build());
        onChanged();
      } else {
        personalInfoRecordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder addPersonalInfoRecords(com.example.grpcprotocol.personalInfo value) {
      if (personalInfoRecordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.add(value);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder addPersonalInfoRecords(
        int index, com.example.grpcprotocol.personalInfo value) {
      if (personalInfoRecordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.add(index, value);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder addPersonalInfoRecords(
        com.example.grpcprotocol.personalInfo.Builder builderForValue) {
      if (personalInfoRecordsBuilder_ == null) {
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.add(builderForValue.build());
        onChanged();
      } else {
        personalInfoRecordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder addPersonalInfoRecords(
        int index, com.example.grpcprotocol.personalInfo.Builder builderForValue) {
      if (personalInfoRecordsBuilder_ == null) {
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.add(index, builderForValue.build());
        onChanged();
      } else {
        personalInfoRecordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder addAllPersonalInfoRecords(
        java.lang.Iterable<? extends com.example.grpcprotocol.personalInfo> values) {
      if (personalInfoRecordsBuilder_ == null) {
        ensurePersonalInfoRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, personalInfoRecords_);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder clearPersonalInfoRecords() {
      if (personalInfoRecordsBuilder_ == null) {
        personalInfoRecords_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public Builder removePersonalInfoRecords(int index) {
      if (personalInfoRecordsBuilder_ == null) {
        ensurePersonalInfoRecordsIsMutable();
        personalInfoRecords_.remove(index);
        onChanged();
      } else {
        personalInfoRecordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public com.example.grpcprotocol.personalInfo.Builder getPersonalInfoRecordsBuilder(
        int index) {
      return getPersonalInfoRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public com.example.grpcprotocol.personalInfoOrBuilder getPersonalInfoRecordsOrBuilder(
        int index) {
      if (personalInfoRecordsBuilder_ == null) {
        return personalInfoRecords_.get(index);  } else {
        return personalInfoRecordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public java.util.List<? extends com.example.grpcprotocol.personalInfoOrBuilder> 
         getPersonalInfoRecordsOrBuilderList() {
      if (personalInfoRecordsBuilder_ != null) {
        return personalInfoRecordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(personalInfoRecords_);
      }
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public com.example.grpcprotocol.personalInfo.Builder addPersonalInfoRecordsBuilder() {
      return getPersonalInfoRecordsFieldBuilder().addBuilder(
          com.example.grpcprotocol.personalInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public com.example.grpcprotocol.personalInfo.Builder addPersonalInfoRecordsBuilder(
        int index) {
      return getPersonalInfoRecordsFieldBuilder().addBuilder(
          index, com.example.grpcprotocol.personalInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .grpcprotocol.personalInfo personalInfoRecords = 4;</code>
     */
    public java.util.List<com.example.grpcprotocol.personalInfo.Builder> 
         getPersonalInfoRecordsBuilderList() {
      return getPersonalInfoRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.grpcprotocol.personalInfo, com.example.grpcprotocol.personalInfo.Builder, com.example.grpcprotocol.personalInfoOrBuilder> 
        getPersonalInfoRecordsFieldBuilder() {
      if (personalInfoRecordsBuilder_ == null) {
        personalInfoRecordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.grpcprotocol.personalInfo, com.example.grpcprotocol.personalInfo.Builder, com.example.grpcprotocol.personalInfoOrBuilder>(
                personalInfoRecords_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        personalInfoRecords_ = null;
      }
      return personalInfoRecordsBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> familyInfo_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetFamilyInfo() {
      if (familyInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FamilyInfoDefaultEntryHolder.defaultEntry);
      }
      return familyInfo_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableFamilyInfo() {
      onChanged();;
      if (familyInfo_ == null) {
        familyInfo_ = com.google.protobuf.MapField.newMapField(
            FamilyInfoDefaultEntryHolder.defaultEntry);
      }
      if (!familyInfo_.isMutable()) {
        familyInfo_ = familyInfo_.copy();
      }
      return familyInfo_;
    }

    public int getFamilyInfoCount() {
      return internalGetFamilyInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */

    @java.lang.Override
    public boolean containsFamilyInfo(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFamilyInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFamilyInfoMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getFamilyInfo() {
      return getFamilyInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getFamilyInfoMap() {
      return internalGetFamilyInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getFamilyInfoOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFamilyInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getFamilyInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetFamilyInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFamilyInfo() {
      internalGetMutableFamilyInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */

    public Builder removeFamilyInfo(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFamilyInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableFamilyInfo() {
      return internalGetMutableFamilyInfo().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */
    public Builder putFamilyInfo(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableFamilyInfo().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; familyInfo = 5;</code>
     */

    public Builder putAllFamilyInfo(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableFamilyInfo().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcprotocol.QueryInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:grpcprotocol.QueryInfoRequest)
  private static final com.example.grpcprotocol.QueryInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpcprotocol.QueryInfoRequest();
  }

  public static com.example.grpcprotocol.QueryInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<QueryInfoRequest>() {
    @java.lang.Override
    public QueryInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryInfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpcprotocol.QueryInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

