// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firstTest.proto

package com.example.grpcprotocol;

public interface QuerySomeDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcprotocol.QuerySomeDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
