// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firstTest.proto

package com.example.grpcprotocol;

public interface subjectMarksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcprotocol.subjectMarks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subjectName = 1;</code>
   * @return The subjectName.
   */
  java.lang.String getSubjectName();
  /**
   * <code>string subjectName = 1;</code>
   * @return The bytes for subjectName.
   */
  com.google.protobuf.ByteString
      getSubjectNameBytes();

  /**
   * <code>double score = 2;</code>
   * @return The score.
   */
  double getScore();
}
